agent_name: mirix
model_name: qwen2-vl-7b-instruct
model_endpoint: http://127.0.0.1:1234/v1
model_provider: local_server
api_key: EMPTY
generation_config:
  temperature: 0.6
  max_tokens: 4096
  context_window: 32768